### ISSUE TITLE
Difference between this and the `byteorder` crate?

### ISSUE THREAD

**Issue by ErichDonGubler** [mvdnes/podio#3]
This seems to have a really similar API to `byteorder` -- are there any differences to speak of besides different identifiers used?

This project seems to have come first, so I'm not here to dispute originality or anything -- just legitimately curious what reason I might have to use this crate over another. :)

**Comment by mvdnes** [comment]
I created this because at the time byteorder seemed to be unnecessary complicated. Nowadays, especially with the inclusion of several functions into the standard library, the existence of podio can be questioned. I keep it around so I can avoid having to rewrite my current projects.
